// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalksAPI.Data;

#nullable disable

namespace NZWalksAPI.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20260326072714_Seeding data for difficulties and regions")]
    partial class Seedingdatafordifficultiesandregions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalksAPI.Models.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fbd4e8ac-4eb5-4199-aefc-4731644fb0ef"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("56da5bcd-0a54-4742-8048-9acec8c0bff8"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("c982ef08-f130-4b09-963b-b4dc44843b2e"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalksAPI.Models.Regions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("56005eaf-7aa7-4244-9b5d-723a25b995c4"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageUrl = "https://images.pexels.com/photos/5342978/pexels-photo-5342978.jpeg"
                        },
                        new
                        {
                            Id = new Guid("7d42bb7b-baa5-4e3c-a3f6-3b554df46f95"),
                            Code = "NTL",
                            Name = "Northland",
                            RegionImageUrl = "null"
                        },
                        new
                        {
                            Id = new Guid("a3bd61b1-638d-4643-a2a8-45be6e6a43b8"),
                            Code = "BOP",
                            Name = "Bay Of Plenty",
                            RegionImageUrl = "null"
                        },
                        new
                        {
                            Id = new Guid("d6a2cb96-f2e3-4417-baa4-b22ad876f4e1"),
                            Code = "WGL",
                            Name = "Wellington",
                            RegionImageUrl = "https://images.pexels.com/photos/33954807/pexels-photo-33954807.jpeg"
                        },
                        new
                        {
                            Id = new Guid("6e73bf95-6faf-4954-b360-5cb197a3ef25"),
                            Code = "NSL",
                            Name = "Nelson",
                            RegionImageUrl = "https://media.istockphoto.com/id/1209995566/photo/panorama-of-nelson-city-reflected-in-the-maitai-river-new-zealand.jpg?s=1024x1024&w=is&k=20&c=ynC5H3sKnrq4Tc4swHlao07JPv13wPEmdwuGG6d7IQE="
                        },
                        new
                        {
                            Id = new Guid("5513d45f-be9e-46df-b40d-cb06e404d552"),
                            Code = "STL",
                            Name = "Southland",
                            RegionImageUrl = "null"
                        });
                });

            modelBuilder.Entity("NZWalksAPI.Models.Walks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalksAPI.Models.Walks", b =>
                {
                    b.HasOne("NZWalksAPI.Models.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalksAPI.Models.Regions", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
